language: cpp
dist: trusty
compiler: g++
sudo: required

services:
  - docker

before_install:
  - docker build -t pardus/hvl-lightdm-greeter .
  - docker run -t -d  --name buildx pardus/hvl-lightdm-greeter 

install:
  - docker exec buildx  /bin/sh -c 'cd /hvl-lightdm-greeter/;mkdir -p build'


script:
  - docker exec buildx  /bin/sh -c 'cd /hvl-lightdm-greeter/build; cmake ..; make'
  - docker exec buildx  /bin/sh -c 'cmake ..'
  - docker exec buildx  /bin/sh -c 'make'
